#### numpy
- Numpy means numerical python
- Numpy is a python library used for working with arrays
- It is a fundamental package for sciencific computing in python
- It is used to create multi dimensional arrays for fast operations
- Numpy arrays are stored at one continuous place in memory
- Using numpy we can perform mathematical and logical operations on arrays
  

# Advantages
- consumes less memory
- fast as compared with python lists
- convinent to use

In [1]:
import numpy

In [2]:
numpy.__version__

'1.26.4'

In [3]:
li = [7,8,9,5,3]
li+3

TypeError: can only concatenate list (not "int") to list

In [5]:
import numpy as np

In [6]:
np.__version__

'1.26.4'

In [ ]:
# creating arrays
- array()

In [7]:
# numpy methods
print(len(dir(np)))

591


In [8]:
# 0-dimensional array
a = np.array(3)
print(a,type(a))

3 <class 'numpy.ndarray'>


In [9]:
# 1-dimensional array
a1 = np.array([1,6,8,9,4])
print(a1,type(a1))

[1 6 8 9 4] <class 'numpy.ndarray'>


In [10]:
a1+5

array([ 6, 11, 13, 14,  9])

In [11]:
# 2- dimensional array
a3 = np.array([[5,6,8],[9,5,8]])
print(a3,type(a3))

[[5 6 8]
 [9 5 8]] <class 'numpy.ndarray'>


In [12]:
a3

array([[5, 6, 8],
       [9, 5, 8]])

In [14]:
a3[0][1]

6

In [15]:
a3[1]

array([9, 5, 8])

In [16]:
# 3- dimensional array
a4 = np.array([[5,6,8],[9,5,8],[8,2,3]])
print(a4,type(a4))

[[5 6 8]
 [9 5 8]
 [8 2 3]] <class 'numpy.ndarray'>


In [22]:
# predefined functions(or) builtin functions in numpy
print(a4)
print(a4.shape) # to get the no of rows and columns
print(a4.ndim) # to get dimensions
print(a4.size) # to get the total no of elements in array
print(a4.dtype) # to get which datatype
print(a4.itemsize) # howmany bytes - 4 bytes

[[5 6 8]
 [9 5 8]
 [8 2 3]]
(3, 3)
2
9
int32
4


In [26]:
# conversion of int to complex
b = np.array([5,7,8,9],dtype='complex')
print(b,b.dtype)

[5.+0.j 7.+0.j 8.+0.j 9.+0.j] complex128


In [25]:
# conversion of int to float
b = np.array([5,7,8,9],dtype='float')
print(b,b.dtype)

[5. 7. 8. 9.] float64


In [28]:
n = np.array([45,78,90,33,89])
print(n)
print(n.max(),n.min(),n.sum())

[45 78 90 33 89]
90 33 335


In [29]:
# using tuple
k = np.array((56,88,66,89))
print(k,type(k))

[56 88 66 89] <class 'numpy.ndarray'>


In [30]:
# using dictionary
k1 = np.array({2:89,"a":"n",9.6:90,66:89})
print(k1,type(k1))

{2: 89, 'a': 'n', 9.6: 90, 66: 89} <class 'numpy.ndarray'>


In [32]:
# range()
n =np.array(range(10))
print(n,type(n))

[0 1 2 3 4 5 6 7 8 9] <class 'numpy.ndarray'>


In [33]:
n1 = np.array(range(10,51))
print(n1)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [34]:
# range with skip count
n1 = np.array(range(10,51,3))
print(n1)

[10 13 16 19 22 25 28 31 34 37 40 43 46 49]


In [35]:
# arange()
n2 = np.array(np.arange(2.5,10.5))
print(n2)

[2.5 3.5 4.5 5.5 6.5 7.5 8.5 9.5]


In [37]:
# linspace()
c2 = np.linspace(10,20,5)
print(c2)

[10.  12.5 15.  17.5 20. ]


In [39]:
# linspace()
c2 = np.linspace(10,20,7,dtype=int)
print(c2)

[10 11 13 15 16 18 20]


In [41]:
# array initialization
# zero's method
a = np.zeros(5)
print(a)
a1 = np.zeros((3,4),dtype=int)
a1

[0. 0. 0. 0. 0.]


array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [42]:
# one's method
a = np.ones(5)
print(a)
a1 = np.ones((3,4),dtype=int)
a1

[1. 1. 1. 1. 1.]


array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [43]:
# identity matrix
print(np.eye(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [44]:
print(np.eye(5,dtype=int))

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [45]:
# 3,4,5 a diagonal values
np.diag([3,4,5])

array([[3, 0, 0],
       [0, 4, 0],
       [0, 0, 5]])

In [47]:
# another method to print identity matrix
n = np.identity(3,dtype=int)
print(n)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [48]:
# diagonal values
np.diag([56,89,3,7,9,3,1])

array([[56,  0,  0,  0,  0,  0,  0],
       [ 0, 89,  0,  0,  0,  0,  0],
       [ 0,  0,  3,  0,  0,  0,  0],
       [ 0,  0,  0,  7,  0,  0,  0],
       [ 0,  0,  0,  0,  9,  0,  0],
       [ 0,  0,  0,  0,  0,  3,  0],
       [ 0,  0,  0,  0,  0,  0,  1]])

In [52]:
# full() # 1-d array
print(np.full(3,7))
print(np.full(5,10))

[7 7 7]
[10 10 10 10 10]


In [54]:
# 2-d array
print(np.full((2,2),3))
print(np.full((5,5),7))

[[3 3]
 [3 3]]
[[7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]]


In [55]:
# 2-d array
li1 = [4,7,9,49]
li2 = [78,99,56,33]
b = np.array([li1,li2])
print(b)

[[ 4  7  9 49]
 [78 99 56 33]]


In [57]:
# arithmetic operations
n1 = np.array([[56,99,66],[89,6,44]])
print("n1 matrix is :")
print(n1)
n2 = np.array([[55,88,99],[23,76,22]])
print("n2 matrix is: ")
print(n2)

n1 matrix is :
[[56 99 66]
 [89  6 44]]
n2 matrix is: 
[[55 88 99]
 [23 76 22]]


In [59]:
print(n1+n2) # addition
print(n1-n2) # substraction
# dot

[[111 187 165]
 [112  82  66]]
[[  1  11 -33]
 [ 66 -70  22]]
