In [ ]:
# Random
    - It is one of the sub module in numpy
    - It is used to generate random numbers

In [1]:
import numpy as np

In [2]:
# print random methods in numpy
r = np.random
print(dir(r))

['BitGenerator', 'Generator', 'MT19937', 'PCG64', 'PCG64DXSM', 'Philox', 'RandomState', 'SFC64', 'SeedSequence', '__RandomState_ctor', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_bounded_integers', '_common', '_generator', '_mt19937', '_pcg64', '_philox', '_pickle', '_sfc64', 'beta', 'binomial', 'bit_generator', 'bytes', 'chisquare', 'choice', 'default_rng', 'dirichlet', 'exponential', 'f', 'gamma', 'geometric', 'get_bit_generator', 'get_state', 'gumbel', 'hypergeometric', 'laplace', 'logistic', 'lognormal', 'logseries', 'mtrand', 'multinomial', 'multivariate_normal', 'negative_binomial', 'noncentral_chisquare', 'noncentral_f', 'normal', 'pareto', 'permutation', 'poisson', 'power', 'rand', 'randint', 'randn', 'random', 'random_integers', 'random_sample', 'ranf', 'rayleigh', 'sample', 'seed', 'set_bit_generator', 'set_state', 'shuffle', 'standard_cauchy', 'standard_exponential', 'standard_gamma', 'sta

In [13]:
# generate single random value
print(np.random.randint(1,100))

78


In [15]:
# generate random values between range
print(np.random.randint(1,50,9))

[ 8 18 28 10 20 31 19 13  1]


In [16]:
# 2d matrix using random
print(np.random.randint(10,30,(2,3)))

[[20 13 27]
 [28 27 11]]


In [18]:
# 2d matrix using random
print(np.random.randint(10,50,(5,5)))

[[48 27 38 19 11]
 [14 20 31 14 11]
 [40 30 10 48 39]
 [40 36 41 41 35]
 [23 43 31 34 34]]


In [22]:
p = np.random.randint(10,30,(3,4))
print(p)
print(p[0]) # 1st row
print(p[1])
print(p[::-1])

[[23 11 14 22]
 [17 20 13 25]
 [28 13 11 28]]
[23 11 14 22]
[17 20 13 25]
[[28 13 11 28]
 [17 20 13 25]
 [23 11 14 22]]


In [23]:
# boolean indexing and fancy indexing
print(p)

[[23 11 14 22]
 [17 20 13 25]
 [28 13 11 28]]


In [24]:
print(p>20)

[[ True False False  True]
 [False False False  True]
 [ True False False  True]]


In [25]:
print(p<20)

[[False  True  True False]
 [ True False  True False]
 [False  True  True False]]


In [26]:
print(p%2==0) # print even numbers

[[False False  True  True]
 [False  True False False]
 [ True False False  True]]


In [27]:
print(p%2!=0) # print odd numbers

[[ True  True False False]
 [ True False  True  True]
 [False  True  True False]]


In [28]:
print(p%5==0)

[[False False False False]
 [False  True False  True]
 [False False False False]]


In [ ]:
# FANCY INDEXING
    - It will returns values


In [29]:
print(p)

[[23 11 14 22]
 [17 20 13 25]
 [28 13 11 28]]


In [31]:
print(p[p%2==0]) # even
print(p[p%2==1]) # odd 

[14 22 20 28 28]
[23 11 17 13 25 13 11]


In [ ]:
# reshape()
    - based on the elements we can reshape the matrix
    - It converts 1-d array to n-d array

In [32]:
# 1-d array
n = np.arange(10)
n

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
# 1-d to 2-d array
n = np.arange(10).reshape(2,5)
print(n)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [34]:
n = np.arange(20).reshape(4,5)
print(n)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [35]:
# slicing
a = np.random.randint(1,30,(10,3))
a

array([[ 2,  9,  1],
       [ 5,  6, 15],
       [16, 18, 25],
       [ 2, 11, 20],
       [17,  1, 21],
       [ 2,  3, 23],
       [ 7, 29, 16],
       [24, 21, 23],
       [ 5, 23, 22],
       [ 1, 18, 13]])

In [36]:
a[0]

array([2, 9, 1])

In [37]:
a[0:3]

array([[ 2,  9,  1],
       [ 5,  6, 15],
       [16, 18, 25]])

In [38]:
a[5:8]

array([[ 2,  3, 23],
       [ 7, 29, 16],
       [24, 21, 23]])

In [39]:
a[-1]

array([ 1, 18, 13])

In [40]:
a[::-1]

array([[ 1, 18, 13],
       [ 5, 23, 22],
       [24, 21, 23],
       [ 7, 29, 16],
       [ 2,  3, 23],
       [17,  1, 21],
       [ 2, 11, 20],
       [16, 18, 25],
       [ 5,  6, 15],
       [ 2,  9,  1]])

In [41]:
a[0::3]

array([[ 2,  9,  1],
       [ 2, 11, 20],
       [ 7, 29, 16],
       [ 1, 18, 13]])

In [42]:
a[0::4]

array([[ 2,  9,  1],
       [17,  1, 21],
       [ 5, 23, 22]])

In [47]:
# sciencific computing
import numpy as np
print(np.log(2))
print(np.log(3))
print(np.log(5))
print(np.log([23,66,78,34,90]))

0.6931471805599453
1.0986122886681098
1.6094379124341003
[3.13549422 4.18965474 4.35670883 3.52636052 4.49980967]


In [53]:
# to print exponential values
print(np.exp(3))
print(np.exp(5))
print(np.exp(7))
print(np.exp([6,7,8,9]))

20.085536923187668
148.4131591025766
1096.6331584284585
[ 403.42879349 1096.63315843 2980.95798704 8103.08392758]


In [54]:
np.sin(0)

0.0

In [55]:
np.tan(30)

-6.405331196646276

In [56]:
np.cos(0)

1.0

In [ ]:
javatpoint.com
w3schools.com

# pandas
    - It means panel data
    - It is one of the data science package
    - It is used for data manupulation,analysis and cleaning
    - It contains mainly 2 data structures
    1.Series :- sequence of data
    2.Data Frames :- data frame is a data with row and column

# how to install pandas 
pip install pandas
# how to install numpy
pip install numpy

In [58]:
import pandas as pd

In [59]:
pd.__version__

'2.2.2'

In [60]:
# creation of series data structure using string
s = "hello"
pd.Series(s)

0    hello
dtype: object

In [61]:
s1 = "hi hello gd evng".split()
pd.Series(s1)

0       hi
1    hello
2       gd
3     evng
dtype: object

In [62]:
li = [67,88,"a","m",8.9]
pd.Series(li)

0     67
1     88
2      a
3      m
4    8.9
dtype: object

In [68]:
li1 = [67,"a",8.9]
d = pd.Series(li1,index=["int","str","float"])
print(type(d))

<class 'pandas.core.series.Series'>


In [69]:
t = ('a','e','i','o','u')
pd.Series(t,index=['v1','v2','v3','v4','v5'])

v1    a
v2    e
v3    i
v4    o
v5    u
dtype: object

In [70]:
li = [34,44,12,55]
sd = pd.Series(li)
print(sd)
print(type(sd))

0    34
1    44
2    12
3    55
dtype: int64
<class 'pandas.core.series.Series'>


In [71]:
sd.index=['A','B','C','D']
sd

A    34
B    44
C    12
D    55
dtype: int64

In [73]:
# creation of series data structure using numpy array
import numpy as np
n = np.array([56,88,99,45,78])
pa = pd.Series(n)
print(pa)
print(type(pa))

0    56
1    88
2    99
3    45
4    78
dtype: int32
<class 'pandas.core.series.Series'>


In [74]:
# using dict
d = {'name':'apssdc','rollno':89,'branch':'cse'}
sd3 = pd.Series(d)
print(sd3)
print(type(sd3))

name      apssdc
rollno        89
branch       cse
dtype: object
<class 'pandas.core.series.Series'>


In [75]:
sd

A    34
B    44
C    12
D    55
dtype: int64

In [76]:
print(sd['A'])

34


In [77]:
sd['C']

12

In [78]:
# TO GET MULTIPLE VALUES
print(sd[:'C'])

A    34
B    44
C    12
dtype: int64


In [79]:
pa

0    56
1    88
2    99
3    45
4    78
dtype: int32

In [80]:
print(sd3)

name      apssdc
rollno        89
branch       cse
dtype: object


In [81]:
sd3['name']

'apssdc'

In [82]:
sd3['branch']

'cse'

In [83]:
print(sd['A':'B'])

A    34
B    44
dtype: int64


In [84]:
# UPDATE THE SERIES VALUES
sd

A    34
B    44
C    12
D    55
dtype: int64

In [85]:
sd['A']=100
sd

A    100
B     44
C     12
D     55
dtype: int64

In [86]:
# replace()
sd = sd.replace(44,120)
sd

A    100
B    120
C     12
D     55
dtype: int64

In [87]:
# update multiple values at a time
sd = sd.replace([12,55],['python','workshop'])
sd

A         100
B         120
C      python
D    workshop
dtype: object

In [88]:
# delete the values
# drop()
sd

A         100
B         120
C      python
D    workshop
dtype: object

In [89]:
sd = sd.drop('C')
sd

A         100
B         120
D    workshop
dtype: object

In [90]:
sd = sd.drop(['A','B'])
sd

D    workshop
dtype: object

In [91]:
# single value to multiple indexes
f = pd.Series('Data Analysis',index=[1,3,7,8,9])
f

1    Data Analysis
3    Data Analysis
7    Data Analysis
8    Data Analysis
9    Data Analysis
dtype: object

In [92]:
pd.Series([10,30,78,88,99,34,90],index=np.arange(1,8))

1    10
2    30
3    78
4    88
5    99
6    34
7    90
dtype: int64

In [93]:
sq = pd.Series(np.arange(10,21)**2,index=np.arange(10,21))
sq

10    100
11    121
12    144
13    169
14    196
15    225
16    256
17    289
18    324
19    361
20    400
dtype: int32

In [94]:
sq[[18,12,13]]

18    324
12    144
13    169
dtype: int32

In [95]:
sq[0:3]

10    100
11    121
12    144
dtype: int32

In [96]:
sq[4:8]

14    196
15    225
16    256
17    289
dtype: int32

In [97]:
sq[::-1]

20    400
19    361
18    324
17    289
16    256
15    225
14    196
13    169
12    144
11    121
10    100
dtype: int32

In [98]:
sq[::2]

10    100
12    144
14    196
16    256
18    324
20    400
dtype: int32

In [99]:
sq[::3]

10    100
13    169
16    256
19    361
dtype: int32

In [100]:
sq[:]

10    100
11    121
12    144
13    169
14    196
15    225
16    256
17    289
18    324
19    361
20    400
dtype: int32